{"name": "test_sauce_demo_invalid_login", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"e0501fa4e3d81c9827809f18b5c4a8d5\")>\n\n    @allure.feature(\"Invalid Login Handling\")  # Group related test cases\n    @allure.story(\"Incorrect Password\")  # D\n    def test_sauce_demo_invalid_login(driver):\n        \"\"\"Test case for the invalid login flow in SauceDemo.\"\"\"\n        automation = SauceDemoAutomation(driver)\n    \n        with allure.step(\"Open SauceDemo website\"):\n            automation.open_website(\"https://www.saucedemo.com/\")\n    \n        with allure.step(\"Log in to SauceDemo\"):\n            automation.login(SAUCEDO_USERNAME, \"invalid_password\")\n    \n        with allure.step(\"Validate error message\"):\n>           automation.validate_error_msg()\n\ntests/main.py:71: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <automation.SauceDemoAutomation object at 0x103463dd0>\n\n    @allure.step(\"Validate error message\")\n    def validate_error_msg(self):\n        error_msg =self.wait.until(EC.presence_of_element_located((By.XPATH, \"//button[@data-test='error-button']\")))\n>       assert \"Epic sadface: Username and password do not match any user in this service\" in error_msg.text\nE       AssertionError\n\ntests/automation.py:77: AssertionError"}, "description": "Test case for the invalid login flow in SauceDemo.", "steps": [{"name": "Open SauceDemo website", "status": "passed", "steps": [{"name": "Open website: 'https://www.saucedemo.com/'", "status": "passed", "parameters": [{"name": "url", "value": "'https://www.saucedemo.com/'"}], "start": 1735178515270, "stop": 1735178515675}], "start": 1735178515270, "stop": 1735178515675}, {"name": "Log in to SauceDemo", "status": "passed", "steps": [{"name": "Login with username: 'standard_user' and password: 'invalid_password'", "status": "passed", "parameters": [{"name": "username", "value": "'standard_user'"}, {"name": "password", "value": "'invalid_password'"}], "start": 1735178515675, "stop": 1735178517732}], "start": 1735178515675, "stop": 1735178517732}, {"name": "Validate error message", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/Users/eitanpeles/Documents/saucedemo/tests/main.py\", line 71, in test_sauce_demo_invalid_login\n    automation.validate_error_msg()\n  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/eitanpeles/Documents/saucedemo/tests/automation.py\", line 77, in validate_error_msg\n    assert \"Epic sadface: Username and password do not match any user in this service\" in error_msg.text\n"}, "steps": [{"name": "Validate error message", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/eitanpeles/Documents/saucedemo/tests/automation.py\", line 77, in validate_error_msg\n    assert \"Epic sadface: Username and password do not match any user in this service\" in error_msg.text\n"}, "start": 1735178517732, "stop": 1735178517744}], "start": 1735178517732, "stop": 1735178517746}], "start": 1735178515270, "stop": 1735178517746, "uuid": "a5e246b3-8275-4f3f-8fd7-d7c0ee21f463", "historyId": "3818446b06c10f618db8fdd812617c07", "testCaseId": "3818446b06c10f618db8fdd812617c07", "fullName": "tests.main#test_sauce_demo_invalid_login", "labels": [{"name": "feature", "value": "Invalid Login Handling"}, {"name": "story", "value": "Incorrect Password"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "main"}, {"name": "host", "value": "ip-192-168-15-3.eu-central-1.compute.internal"}, {"name": "thread", "value": "54372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.main"}]}